[build-system]
requires = ["setuptools ~= 58.0", "cython ~= 0.29.0", "certifi == 2021.5.30", "chardet == 4.0.0", "idna == 2.10", "PySocks == 1.7.1", "requests == 2.25.1", "urllib3 == 1.26.5", "httpx == 0.22.0"]
packages = ['proxy_checking]